### ISSUE TITLE
Issue with downloading 1.3 - download never finishes

### ISSUE THREAD

**Issue by mmcgirr** [portacle/portacle#114]
Hello,

Attempting to download 1.3 on windows 10 (5/12/19).  Product downloads (gets to 100%), but then never finishes the download proper.  

Not sure even where to begin with this, as it's the only time I've ever encountered it in the wild.

Running Chrome 74.0.3729.131 (Official Build) (64-bit), on Windows 10 64-bit (build 1803, 17134.706).  

Have tried to download the same thing with MS edge and so forth as well.

Thanks!

**Comment by Shinmera** [comment]
I don't host the downloads, that's github, so this is completely out of my hands. Sorry!

**Comment by nikofeyn** [comment]
What happens if you click on the download to try and run it? I just had an issue similar to this (maybe not the same), but it seems it had to do with the Windows virus and threat defender running. When I clicked on the Portacle download to run it, I got the warning that this application was downloaded from the Internet and couldn't be verified, and then I had to click the "Run anyway" button. It took a little bit after I clicked it from Chrome to get this dialog. I don't know how Windows 10 verifies applications.
