### ISSUE TITLE
installation on macos involves authorizing every subprogram and dylib

### ISSUE THREAD

**Issue by louisabraham** [portacle/portacle#158]
I followed the instructions but still get a TON of those prompts. Every time I have to autorize the program in System Preferences, then get another prompt. I got this for at least 8 programs, like git, sbcl, emacs, libffi, etc

<img width="328" alt="image" src="https://user-images.githubusercontent.com/13174805/142011705-8c840076-0b34-4697-a80e-6df147c5f6f5.png">

**Comment by metayan** [comment]
In `Preferences`-`Security&Privacy`-`Privacy` tab, I choose `Full Disk Access` on the left and click `Portacle.app` on the right every time macOS starts complaining, which is whenever I rebuild or reinstall it, so quite seldom.

**Comment by Rcsuax** [comment]
> In `Preferences`-`Security&Privacy`-`Privacy` tab, I choose `Full Disk Access` on the left and select `Portacle.app` on the right every time macOS starts complaining, which is whenever I rebuild or reinstall it, so quite seldom.
> 
> Works for Catalina, but one can hope that there is some similar way even on newer versions of macOS.

This doesn't work.
I had to manually approve each prompt which was frustrating to say the least 
<img width="588" alt="Screenshot 2021-12-30 at 18 34 36" src="https://user-images.githubusercontent.com/18594905/147779451-32ceaedf-2903-4304-8980-83334a4b1fdd.png">

**Comment by StephenTaylor-Kx** [comment]
Same for Big Sur. And why am I authorising Git, already installed on macOS, and what are the implications for my existing (extensive) use of Git? Can Portacle not be delivered better through Homebrew?

**Comment by Shinmera** [comment]
@StephenTaylor-Kx Because portacle is an independent package, it ships git. The implications are "you have another git copy inside portacle". The point of portacle is to offer an archive that delivers a full IDE in one step. Having to first install homebrew would defeat that. Also, since Portacle is a sort of meta-package, I don't think it would be accepted into Homebrew's set of recipes.

**Comment by Shinmera** [comment]
Otherwise, please try the latest pre-release: https://github.com/portacle/portacle/releases/tag/1.4c
It was created under macOS 12, so it may not launch on older versions. I'd be interested to know about that.
It's been signed using a self-signed certificate, which must first be installed using the mac-fixup.sh script. The script will also clear security attributes. Unfortunately there's no way to make the script runnable via a simple double-click, so it has to be done via the terminal.

Closing this, as all mac problems are pretty much the same atm. Please continue discussions in #127
