### ISSUE TITLE
MacOS .dmg doesn't look like usual "drag to install" disk image, fails with "unknown developer" 

### ISSUE THREAD

**Issue by genworks** [portacle/portacle#51]
In my experience, MacOS .dmg's usually present an ISO disk volume with a customized finder window to "drag to install" an Application into the /Applications folder.  Alternatively it shows up as one toplevel Application with an icon (and you can see the contents by right-clicking and choosing "Show Package Contents"). The Mac version of Portacle doesn't look like this - it just presents a folder in-place. 

Moreover, if I try to launch what appears to be the Portacle executable, I'm getting thwarted by MacOS, telling me "Portable can't be opened because it is from an unidentified developer." 

We can possibly help with this (our organization does have a Mac Developer ID certificate), but I'm not sure if the Portacle project would want our organization's certificate on the distribution, and I'm not sure what the intended packaging is supposed to look like. 

We have been distributing something like Portacle but with pre-built images of Gendl (an open-source KBE system built on CL) rather than vanilla CL. 

Portacle might make for a smoother and more standardized way for us to distribute these "convenience" Gendl builds, or at least as a basis for doing that, but I'll have to understand more about how the packaging is expected to be.  Also, we are distributing with CCL as the included CL engine. Has the Portacle project considered including more than one CL engine by default?

**Comment by genworks** [comment]
I should have opened my Issue with  some words of encouragement -- I think Portacle is an essential product/service for the CL community, because so many hopeful newcomers get put off with complicated setup steps for an initial development environment (as usual, so many different ways to do it!) So to have a defact standard "quickstart" way to get up and running with an environment, along the lines of the Lispbox effort of yore, is quite welcome and a positive step for the community.

**Comment by Shinmera** [comment]
Unfortunately it's not possible for Portacle to be deployed as a standalone .app, as it touches a lot of files in folders surrounding it, and the user is supposed to be able to reach them and manage them easily-- they are not supposed to be "internal parts of the program."

However, you can instead drag and drop the portacle folder anywhere you want and, after following the [additional steps outlined on the website](https://portacle.github.io/#get-mac), run Portacle like anything else.

I'm well aware of the annoying unidentified developer blockage and I would like to get rid of it, but not with an ID that is not specifically geared for Portacle and under control of an official Portacle developer. Since I do not have any kind of stable income right now, I'm not ready to pay a 100$ a year for an Apple developer license.

What you could do instead is build Portacle yourself and then sign the .app it produces. Note that the .app is merely a shim with a script that calls out to applications outside of itself, due to the aforementioned architecture decisions.

I have given some thought to deploying alternate lisp implementations instead of SBCL, specifically CCL and ECL, and would be open to inclusion thereof. I have not done anything to facilitate this yet, however.

What would need to be done to get support for one is:

1. Create a build script that will completely automatically:
1.1. Download the necessary source code
1.2. Set up the build and perform it
1.3. Install the build result into the proper place according to Portacle's architecture
2. Adapt the [startup script](https://github.com/portacle/config/blob/master/sbcl-init.lisp) to work with the implementation
3. Test and potentially adapt the build so that it works on all three supported platforms

As for packaging Gendl or some other software with it, what you would want to do is add another build step in the form of a new script that, similar to the [quicklisp.sh](https://github.com/portacle/portacle/blob/master/build/quicklisp.sh), runs some CL code to ensure the necessary software is installed and included in the local build tree. You'd then possibly also want to modify the init script mentioned above to also load your software right away, and possibly adapt help files and scratch buffer text to suit your needs, etc. Thus it shouldn't take much effort to get that integrated.

I've also been thinking of turning Portacle into a sort of Platform to deliver applications with an IDE with, similar to what you seem to desire. However, so far, nothing has been put in place yet to make that trivial.

**Comment by Shinmera** [comment]
I'll close this since there doesn't seem to be any more discussion going on. Feel free to re-open as convenient.
