### ISSUE TITLE
Locale Unsupported

### ISSUE THREAD

**Issue by Shinmera** [portacle/portacle#63]
Currently Portacle forces the locale to en_US.UTF-8. However, the system might not have this locale generated. For that case, Portacle should ship its own locale files.

**Comment by m3m0ry** [comment]
Might this be the source of my problem?

`emacs: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
 stack smashing detected : /home/hrom/Downloads/portacle//lin/launcher/portacle terminated
./portacle.run: line 7:  8492 Aborted                 "$ROOT/lin/launcher/portacle" "$@"`

However i tried all kinds of  language settings.
In deiban i even installed locales-all in order to have all locales "generated"

**Comment by Shinmera** [comment]
No. See #60.

**Comment by m3m0ry** [comment]
Yeah the report is stack smashing. And that portacle is terminated.
But that's not the problem, that's just a symptom. (please explain to me if it's not)

Something is somehow broken with my locales and i don't know what and why.
It might be that i am not using en_US.UTF-8 everywhere on my machine.
I will double check it and report back.

`emacs: loadlocale.c:129: _nl_intern_locale_data: Assertion``cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.`
