### ISSUE TITLE
nsswitch.conf Can Load Libraries from the Host System

### ISSUE THREAD

**Issue by Wilfred** [portacle/portacle#68]
I'm unable to run Portacle on Arch Linux.

I tried downloading the pre-built version and ran it as follows:

```
$ ./portacle.run
Inconsistency detected by ld.so: dl-open.c: 689: _dl_open: Assertion `_dl_debug_initialize (0, args.nsid)->r_state == RT_CONSISTENT' failed!
```

According to [this SO question](https://stackoverflow.com/q/22564780/509706) I can use `LD_DEBUG`:

```
$ LD_DEBUG=symbols,bindings ./portacle.run
... snip
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/emacs/bin/emacs [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libXpm.so.4 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libgtk-x11-2.0.so.0 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libgdk-x11-2.0.so.0 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libgio-2.0.so.0 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libgdk_pixbuf-2.0.so.0 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libfontconfig.so.1 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libgobject-2.0.so.0 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libfreetype.so.6 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libglib-2.0.so.0 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libSM.so.6 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libICE.so.6 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libX11.so.6 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libX11-xcb.so.1 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libxcb.so.1 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libXrender.so.1 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libXft.so.2 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/librt.so.1 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libXfixes.so.3 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libtinfo.so.5 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libgnutls.so.26 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libpthread.so.0 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libm.so.6 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libz.so.1 [0]
     11312:	symbol=getaddrinfo;  lookup in file=/home/wilfred/src/portacle//lin/lib/libc.so.6 [0]
     11312:	binding file /home/wilfred/src/portacle//lin/emacs/bin/emacs [0] to /home/wilfred/src/portacle//lin/lib/libc.so.6 [0]: normal symbol `getaddrinfo' [GLIBC_2.2.5]
     11312:	symbol=_nss_files_gethostbyname4_r;  lookup in file=/home/wilfred/src/portacle//lin/lib/libnss_files.so.2 [0]
     11312:	binding file /home/wilfred/src/portacle//lin/lib/libnss_files.so.2 [0] to /home/wilfred/src/portacle//lin/lib/libnss_files.so.2 [0]: normal symbol `_nss_files_gethostbyname4_r'
     11312:	/home/wilfred/src/portacle//lin/lib/libc.so.6: error: version lookup error: version `GLIBC_2.25' not found (required by /usr/lib/libnss_mymachines.so.2) (fatal)
Inconsistency detected by ld.so: dl-open.c: 689: _dl_open: Assertion `_dl_debug_initialize (0, args.nsid)->r_state == RT_CONSISTENT' failed!
```

Looks like an issue with my version of glibc? I have 2.26 installed.

I tried building from source instead:

```
$ git clone  ....
$ cd portacle_git/build
$ ./build.sh
```

This succeeds, but it's not clear to me how to use it. I didn't spot anything in the readme. I can see a `portacle.run` file, but that can't find lin:

```
~/src/portacle_git/build/src 
$ ./portacle.run    
./portacle.run: line 7: /home/wilfred/src/portacle_git/build/src//lin/launcher/portacle: No such file or directory
```

What am I doing wrong?

**Comment by Shinmera** [comment]
The error is that somehow `/usr/lib/libnss_mymachines.so.2` is getting loaded from your system, rather than from Portacle's own distribution, which messes things up badly for obvious reasons. This is a leak and needs to be stuffed, so it's a bug in Portacle's distribution.

If the build indeed succeeds properly, you should be able to use the `portacle.run` or desktop file in the root directory of Portacle. If for some reason this doesn't work, try running `package.sh`, which should produce a distribution package like the one you can download in the `package` directory.

**Comment by Wilfred** [comment]
The build seems to have succeeded, but I don't have a `portacle.run` in the root directory:

```$ ./build.sh 
 ==>  portacle build info:
Platform:           lin
Downloading from:   https://github.com/Shinmera/portacle
Using tag:          1.1-1-gaec2093
Building in:        /home/wilfred/src/portacle_git/build
Installing into:    /home/wilfred/src/portacle_git/lin/portacle/
Using threads:      3
Building targets:   download upgrade package

   ->  downloading portacle
From https://github.com/portacle/portacle
 * branch            master     -> FETCH_HEAD
Already up to date.
   ->  upgradeing portacle
     >  skipping upgrade, already completed
   ->  packageing portacle
     >  skipping package, already completed
 ==>  portacle done
~/src/portacle_git/build 
$ cd ..
~/src/portacle_git 
$ ls
all/  build/  config/  CONTRIBUTING.md  lin/  package/  README.md
```

I can see two portacle.run files, but both fail with different errors:

```
$ find . -name portacle.run
./build/src/portacle.run
./package/portacle/portacle.run
$ ./build/src/portacle.run 
./build/src/portacle.run: line 7: /home/wilfred/src/portacle_git/build/src//lin/launcher/portacle: No such file or directory
$ ./package/portacle/portacle.run 
emacs: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs
```

**Comment by Shinmera** [comment]
Ah balls. Looks like you've hit the classic #18 . I'll see what I can do to plug the libnss leak sometime soon, so I guess you'll have to wait until then.

**Comment by gonzalezjo** [comment]
I have this same issue, down to the same library (libnss_mymachines.so.2)


I _am_ using a variant of Arch (Antergos), rather than vanilla Arch, but I would not expect that to cause any issues.


Here's an excerpt from `strace`: 

<details>
<summary>Spoiler (Click to show)</summary>
--- SIGIO {si_signo=SIGIO, si_code=SI_KERNEL} ---
rt_sigreturn({mask=[]})                 = 44
recvmsg(5, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\f\0s\207K\0\0\4\370\2&\2\2\0\202\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
recvmsg(5, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=6, events=POLLIN}, {fd=5, events=POLLIN}], 2, 0) = 0 (Timeout)
poll([{fd=6, events=POLLIN}, {fd=5, events=POLLIN}], 2, 0) = 0 (Timeout)
poll([{fd=5, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=5, revents=POLLOUT}])
writev(5, [{iov_base="=\0\4\0K\0\0\4\370\2&\2\2\0\202\2;\0\5\0T\0\0\4\0\0\0\0\0\0 \2"..., iov_len=8216}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 8216
recvmsg(5, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(5, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=6, events=POLLIN}, {fd=5, events=POLLIN}], 2, 0) = 0 (Timeout)
recvmsg(5, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=6, events=POLLIN}, {fd=5, events=POLLIN}], 2, 0) = 0 (Timeout)
poll([{fd=5, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=5, revents=POLLOUT}])
writev(5, [{iov_base="5\30\4\0\363\4\0\4K\0\0\4\2\0\202\0026\0\2\0\363\4\0\4", iov_len=24}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 24
recvmsg(5, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(5, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=6, events=POLLIN}, {fd=5, events=POLLIN}], 2, 0) = 0 (Timeout)
read(11, "", 4096)                      = 0
close(11)                               = 0
munmap(0x7fa2b43d2000, 4096)            = 0
rt_sigprocmask(SIG_BLOCK, [INT ALRM], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
open("/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 11
fstat(11, {st_mode=S_IFREG|0644, st_size=127, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa2b43d2000
read(11, "# Generated by NetworkManager\nse"..., 4096) = 127
read(11, "", 4096)                      = 0
close(11)                               = 0
munmap(0x7fa2b43d2000, 4096)            = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 11
connect(11, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(11)                               = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 11
connect(11, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(11)                               = 0
open("/etc/host.conf", O_RDONLY|O_CLOEXEC) = 11
fstat(11, {st_mode=S_IFREG|0644, st_size=73, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa2b43d2000
read(11, "# Resolver configuration file.\n#"..., 4096) = 73
--- SIGIO {si_signo=SIGIO, si_code=SI_TKILL, si_pid=22021, si_uid=1000} ---
rt_sigreturn({mask=[]})                 = 73
read(11, "", 4096)                      = 0
close(11)                               = 0
munmap(0x7fa2b43d2000, 4096)            = 0
futex(0x7fa2bb70d3d0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
stat("/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=127, ...}) = 0
open("/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 11
fstat(11, {st_mode=S_IFREG|0644, st_size=127, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa2b43d2000
read(11, "# Generated by NetworkManager\nse"..., 4096) = 127
read(11, "", 4096)                      = 0
close(11)                               = 0
munmap(0x7fa2b43d2000, 4096)            = 0
open("/etc/hosts", O_RDONLY|O_CLOEXEC)  = 11
fstat(11, {st_mode=S_IFREG|0644, st_size=65, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa2b43d2000
read(11, "# Static table lookup for hostna"..., 4096) = 65
read(11, "", 4096)                      = 0
close(11)                               = 0
munmap(0x7fa2b43d2000, 4096)            = 0
open("/home/john/Portacle/test2//lin/lib/libnss_mymachines.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 11
fstat(11, {st_mode=S_IFREG|0644, st_size=434428, ...}) = 0
mmap(NULL, 434428, PROT_READ, MAP_PRIVATE, 11, 0) = 0x7fa2a7cf7000
close(11)                               = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/usr/lib/libnss_mymachines.so.2", O_RDONLY|O_CLOEXEC) = 11
read(11, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0PQ\0\0\0\0\0\0"..., 832) = 832
fstat(11, {st_mode=S_IFREG|0755, st_size=263184, ...}) = 0
mmap(NULL, 2359288, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 11, 0) = 0x7fa2a7a3e000
mprotect(0x7fa2a7a7b000, 2093056, PROT_NONE) = 0
mmap(0x7fa2a7c7a000, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 11, 0x3c000) = 0x7fa2a7c7a000
close(11)                               = 0
munmap(0x7fa2a7cf7000, 434428)          = 0
writev(2, [{iov_base="Inconsistency detected by ld.so:"..., iov_len=33}, {iov_base="dl-open.c", iov_len=9}, {iov_base=": ", iov_len=2}, {iov_base="689", iov_len=3}, {iov_base=": ", iov_len=2}, {iov_base="_dl_open", iov_len=8}, {iov_base=": ", iov_len=2}, {iov_base="Assertion `", iov_len=11}, {iov_base="_dl_debug_initialize (0, args.ns"..., iov_len=61}, {iov_base="' failed!\n", iov_len=10}], 10) = 141
exit_group(127)                         = ?
+++ exited with 127 +++
</details>

**Comment by Shinmera** [comment]
Okey, for some reason it tries to load `libnss_mymachines` on your systems but not on mine. Can you post `/etc/nsswitch.conf` and `strace -f -e trace=open ./portacle.run`?

**Comment by Shinmera** [comment]
My prediction is that your nsswitch will load mymachines in. I'm not entirely sure how to deal with this situation. Parts of the ns information must come from the host, but this also means that the configuration might try to load in ns plugins that Portacle doesn't provide, leading to a crash. I also don't see a way to tell libc to load `nsswitch.conf` from anywhere else but `/etc`.

**Comment by gonzalezjo** [comment]
/etc/nsswitch.conf: https://hastebin.com/uvagedodak

strace logs: [logs.txt](https://github.com/portacle/portacle/files/1825873/logs.txt)

**Comment by Shinmera** [comment]
Thanks.

Looks like my idea is indeed accurate. It starts up fine, then gets to the point where it tries to do a DNS lookup (probably melpa), which loads in libnss_mymachines as specified in nsswitch.

Aside from that, the following lines are also worrying me a bit, though they don't seem to cause any immediate problems:

```
28171 open("/usr/lib/gio/modules/giomodule.cache", O_RDONLY) = 8
28171 open("/usr/lib/gio/modules/libdconfsettings.so", O_RDONLY|O_CLOEXEC) = 7
28171 open("/usr/lib/gio/modules/libgsettingsgconfbackend.so", O_RDONLY|O_CLOEXEC) = 7
28171 open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 7
28171 open("/usr/lib/libgconf-2.so.4", O_RDONLY|O_CLOEXEC) = 7
28171 open("/usr/lib/libdbus-glib-1.so.2", O_RDONLY|O_CLOEXEC) = 7
28171 open("/usr/lib/libdbus-1.so.3", O_RDONLY|O_CLOEXEC) = 7
28171 open("/usr/lib/libsystemd.so.0", O_RDONLY|O_CLOEXEC) = 7
28171 open("/usr/lib/liblz4.so.1", O_RDONLY|O_CLOEXEC) = 7
28171 open("/usr/lib/libgcrypt.so.20", O_RDONLY|O_CLOEXEC) = 7
```

**Comment by Shinmera** [comment]
I'm looking into writing stub replacements for modules like mymachines, but that's not great either.

There doesn't seem to be a way to tell glibc to look at another file than `/etc/nsswitch.conf` for the module info, but even if it were it wouldn't be a great solution since it would circumvent legitimate configurations on some systems.

**Comment by gonzalezjo** [comment]
That definitely sounds like the cleanest option for now, even if it's sub-optimal. I don't think that mymachines or myhostname would cause any issues w/regards to different configurations, in the context of an IDE.

**Comment by Shinmera** [comment]
Okey, here's my idea for an ideal solution, which seems feasible, and I might implement some day_

We implement a new, static binary `host-bridge`. This static binary will be executed in the host environment and can make calls to the host's `glibc` via `dlopen` and `dlsym`. We then implement shims for all `nss` libraries, but instead of delegating to the `dns` module by default like we do now for mymachines etc., we open a subprocess to the host-bridge binary that will execute the requested call in the host environment. Since the host binary will be in an untainted environment, it should be able to open the host's libraries and relay the necessary information back to the "in-portacle" process.

This is definitely roundabout and makes me wrinkle my nose in disgust, but it seems like a workable way to bridge the two worlds in cases where it is absolutely necessary like here.

**Comment by Shinmera** [comment]
Here's the promised package: https://github.com/portacle/portacle/releases/tag/1.1b

**Comment by Wilfred** [comment]
It works! :tada: :tada: 

Thanks.

Regarding https://github.com/portacle/portacle/issues/68#issuecomment-374019082 I couldn't get it working from source as of two days ago on latest Arch, but the provided compiled version works nicely :)

**Comment by Shinmera** [comment]
Great!

**Comment by gonzalezjo** [comment]
Works for me too!
