### ISSUE TITLE
How to just enter " or )

### ISSUE THREAD

**Issue by BenKey** [portacle/portacle#94]
I am having enormous difficulties typing lisp code in Portacle, is a complete IDE for Common Lisp based on Emacs. It is trying to get cute whenever I enter a " or a ). Sometimes it breaks my code.

Scenario 1.

I had the following in the clipboard.

    (substitute-in-file-name "${SystemDrive}/opt

I pasted this at the end of a line that already had the following text.

    ((file-directory-p 

The result was the following line of text.

    ((file-directory-p (substitute-in-file-name "${SystemDrive}/opt

I then typed a " at the end of this line.

Portacle escaped the " so that the final result was as follows.

    ((file-directory-p (substitute-in-file-name "${SystemDrive}/opt\"

Portacle does similar nonsense when I try to type ).

How do I get " to simply put a " where my caret is instead of getting cute.

**Comment by Shinmera** [comment]
This is more of a paredit question, since that's the package that causes this behaviour.

Paredit automatically tries to balance the structure of your code to keep it valid at all times. When you break this structure by pasting invalid code, it can't really know what to do. However, since you know that you can paste broken code, you can also fix it in the same way, by pasting in the missing pieces, or cutting out the offending pieces.
