### ISSUE TITLE
Hyperspec lookup doesn't work on macOS

### ISSUE THREAD

**Issue by bitmason** [portacle/portacle#96]
New users are guided to the `*portacle-help*` tutorial which suggests looking up a symbol with: `C-c C-h d`

As a macOS user (Mojave 10.14), I receive this error: **Searching for program: No such file or directory, xdg-open**

**Comment by jorams** [comment]
This happens because `browse-url-browser-function` is set in two places:

- [`portacle-general.el`](https://github.com/portacle/emacsd/blob/c0672a36b32d2b0c8dfb893fabd875a2cde120aa/portacle-general.el#L35-L42)
- [`portacle-window.el`](https://github.com/portacle/emacsd/blob/c0672a36b32d2b0c8dfb893fabd875a2cde120aa/portacle-window.el#L15-L16)

The first one executes first and is portable, but the second one overrides it and is not portable. One way to fix this would be to move the implementation from `portacle-general.el` to `portacle-window.el`, but I looked into `browse-url-browser-function` a bit and I don't see why portacle should set it at all. The default value of `browse-url-default-browser` is much more portable.

**Comment by Shinmera** [comment]
I believe the override exists (in theory) so that it can open file paths in the apropriate program, which is not always the web browser. I'm not 100% on this, though the definitions as they stand are clearly wrong.

**Comment by Shinmera** [comment]
I think the proper action would be to just get rid of the definitions in `portacle-window.el` for now.

**Comment by jorams** [comment]
- The default implementation uses `xdg-open` on linux, `open` on macOS, and the Win32 API function `ShellExecute` with the verb `open` on Windows.
- The implementation in `portacle-general.el` uses `xdg-open` on linux, `open` on macOS, and the program `start` on Windows. `start`, in turn which appears to be doing the same thing when given a URL as `ShellExecute` with the verb `open`.

I'm not sure if there's an actual behind-the-scenes difference between the two Windows approaches, but the linux and macOS implementations appear to be equivalent, except for the fact that `browse-url-default-browser` has many more fallbacks and checks.

Removing both definitions makes the most sense to me.

**Comment by Shinmera** [comment]
I see. I think this hack might have been necessary at some point in the past, but it isn't anymore now. Removing both is fine by me then.
